### PR TITLE
Retry on connection error or timeout

### PR DESCRIPTION
**Pull request by Ebag333**
Wraps `self._request` in a `try`\`except` and if we get an exception of `ConnectionError` or `ConnectTimeout` will set it up so we retry the connection.

### CODE REVIEW

**Comment by Kyria** [comment]
What case do your PR cover actually? 

I don't feel like it's a good idea to catch and retry timeout, especially as it seems not to raise any exceptions actually (`requests.Response` have a `raise_for_status()` method for this).
It tested many time the timeout error (HTTP 504), and every time I have a timeout, it retries 5 times, and I get a `pyswagger.io.Response` with status = 504... So I don't really understand the need of this try/except. 

If it's only for SSL errors, since this comes from the client config and not from ESI most of the time (within a few month, with ~3000-5000 requests per days, I never had it), it'd better to find the root cause of the issue instead of patching esipy client :confused: 

Also, regarding the commits themself, can't you use a `pyswagger.io.Response` object instead of creating a whole new class ?

_FYI, I also tested `requests` on a simple page that triggers a timeout on my nginx server (php page with a sleep(180sec)), and `requests` do not raise any exceptions too, only a `Response` with a status code 504_

-----------------

Versions in my test env, FYI, if you want to compare :
```
python 2.7.9
pip 9.0.1

pyswagger==0.8.29
requests==2.13.0
futures==3.1.1
six==1.10.0
```

-----------------

Little test I made to cover timeout, just to see if it raises exceptions or return the Response:
* test/mock.py
```python

@httmock.urlmatch(
    scheme="https",
    netloc=r"esi\.tech\.ccp\.is$",
    path=r"^/latest/incursions/$"
)
def public_incursion_timeout(url, request):
    """ Mock endpoint for incursion.
    Public endpoint with timeout error
    """
    public_incursion_timeout.count += 1
    return httmock.response(
        status_code=504,
        content={
            "error": "504 Gateway Timeout",
            "count": public_incursion_timeout.count
        }
    )

public_incursion_timeout.count = 0
```

* test/test_client.py
```python
    def test_esipy_timeout(self):
        operation = self.app.op['get_incursions']()
        with httmock.HTTMock(public_incursion_timeout):
            incursions = self.client_no_auth.request(operation)
            self.assertEqual(
                json.loads(incursions.raw)['error'],   # we use .raw because it looks like timeout do not fill .data 
                '504 Gateway Timeout'
            )
        self.assertEqual(json.loads(incursions.raw)['count'], 5)
```

**Comment by Ebag333** [comment]
>What case do your PR cover actually?
>I don't feel like it's a good idea to catch and retry timeout, especially as it seems not to raise any exceptions actually (requests.Response have a raise_for_status() method for this).
It tested many time the timeout error (HTTP 504), and every time I have a timeout, it retries 5 times, and I get a pyswagger.io.Response with status = 504... So I don't really understand the need of this try/except.

On a spotty network connection, you can see a number of similar stacktraces.  It does actually stacktrace, and it gets passed up which causes the code to bomb when I'd expect it to retry.

A retry works fine, I never saw the issue occur twice in a row.

There's the stacktrace I pasted for you:
```
[2017-04-24 16:44:27.175000] CRITICAL: __main__: Exception in main thread: EOF occurred in violation of protocol (_ssl.c:661)
[2017-04-24 16:44:27.175000] WARNING: __main__:   File "C:\Program Files (x86)\JetBrains\PyCharm 2016.3.2\helpers\pydev\pydevd.py", line 1578, in <module>
[2017-04-24 16:44:27.175000] WARNING: __main__:     globals = debugger.run(setup['file'], None, None, is_module)
[2017-04-24 16:44:27.176000] WARNING: __main__:   File "C:\Program Files (x86)\JetBrains\PyCharm 2016.3.2\helpers\pydev\pydevd.py", line 1015, in run
[2017-04-24 16:44:27.176000] WARNING: __main__:     pydev_imports.execfile(file, globals, locals)  # execute the script
[2017-04-24 16:44:27.177000] WARNING: __main__:   File "./pyfa.py", line 389, in <module>
[2017-04-24 16:44:27.177000] WARNING: __main__:     sESI.updateTypes()
[2017-04-24 16:44:27.177000] WARNING: __main__:   File ".\service\esi.py", line 111, in updateTypes
[2017-04-24 16:44:27.177000] WARNING: __main__:     self.updateTypesData(esi_type_list)
[2017-04-24 16:44:27.178000] WARNING: __main__:   File ".\service\esi.py", line 120, in updateTypesData
[2017-04-24 16:44:27.178000] WARNING: __main__:     threads=50,
[2017-04-24 16:44:27.178000] WARNING: __main__:   File "C:\Python27\lib\site-packages\esipy\client.py", line 146, in multi_request
[2017-04-24 16:44:27.179000] WARNING: __main__:     for result in pool.map(_multi_shim, reqs_and_resps):
[2017-04-24 16:44:27.179000] WARNING: __main__:   File "C:\Python27\lib\site-packages\concurrent\futures\_base.py", line 605, in result_iterator
[2017-04-24 16:44:27.179000] WARNING: __main__:     yield future.result()
[2017-04-24 16:44:27.179000] WARNING: __main__:   File "C:\Python27\lib\site-packages\concurrent\futures\_base.py", line 429, in result
[2017-04-24 16:44:27.180000] WARNING: __main__:     return self.__get_result()
[2017-04-24 16:44:27.180000] WARNING: __main__:   File "C:\Python27\lib\site-packages\concurrent\futures\thread.py", line 62, in run
[2017-04-24 16:44:27.180000] WARNING: __main__:     result = self.fn(*self.args, **self.kwargs)
[2017-04-24 16:44:27.180000] WARNING: __main__:   File "C:\Python27\lib\site-packages\esipy\client.py", line 140, in _multi_shim
[2017-04-24 16:44:27.180000] WARNING: __main__:     opt=opt,
[2017-04-24 16:44:27.181000] WARNING: __main__:   File "C:\Python27\lib\site-packages\esipy\client.py", line 99, in _retry_request
[2017-04-24 16:44:27.181000] WARNING: __main__:     res = self._request(req_and_resp, **kwargs)
[2017-04-24 16:44:27.181000] WARNING: __main__:   File "C:\Python27\lib\site-packages\esipy\client.py", line 211, in _request
[2017-04-24 16:44:27.181000] WARNING: __main__:     stream=True
[2017-04-24 16:44:27.182000] WARNING: __main__:   File "C:\Python27\lib\site-packages\requests\sessions.py", line 596, in send
[2017-04-24 16:44:27.182000] WARNING: __main__:     r = adapter.send(request, **kwargs)
[2017-04-24 16:44:27.182000] WARNING: __main__:   File "C:\Python27\lib\site-packages\requests\adapters.py", line 497, in send
[2017-04-24 16:44:27.182000] WARNING: __main__:     raise SSLError(e, request=request)
```

I also saw this one:
```
[2017-04-24 07:07:21.290000] CRITICAL: __main__: Exception in main thread: EOF occurred in violation of protocol (_ssl.c:661)
[2017-04-24 07:07:21.290000] WARNING: __main__:   File "C:\Program Files (x86)\JetBrains\PyCharm 2016.3.2\helpers\pydev\pydevd.py", line 1578, in <module>
[2017-04-24 07:07:21.291000] WARNING: __main__:     globals = debugger.run(setup['file'], None, None, is_module)
[2017-04-24 07:07:21.291000] WARNING: __main__:   File "C:\Program Files (x86)\JetBrains\PyCharm 2016.3.2\helpers\pydev\pydevd.py", line 1015, in run
[2017-04-24 07:07:21.291000] WARNING: __main__:     pydev_imports.execfile(file, globals, locals)  # execute the script
[2017-04-24 07:07:21.292000] WARNING: __main__:   File "./pyfa.py", line 389, in <module>
[2017-04-24 07:07:21.292000] WARNING: __main__:     sESI.updateTypes()
[2017-04-24 07:07:21.292000] WARNING: __main__:   File ".\service\esi.py", line 111, in updateTypes
[2017-04-24 07:07:21.292000] WARNING: __main__:     self.updateTypesData(esi_type_list)
[2017-04-24 07:07:21.293000] WARNING: __main__:   File ".\service\esi.py", line 120, in updateTypesData
[2017-04-24 07:07:21.293000] WARNING: __main__:     threads=50,
[2017-04-24 07:07:21.293000] WARNING: __main__:   File "C:\Python27\lib\site-packages\esipy\client.py", line 146, in multi_request
[2017-04-24 07:07:21.293000] WARNING: __main__:     for result in pool.map(_multi_shim, reqs_and_resps):
[2017-04-24 07:07:21.294000] WARNING: __main__:   File "C:\Python27\lib\site-packages\concurrent\futures\_base.py", line 605, in result_iterator
[2017-04-24 07:07:21.294000] WARNING: __main__:     yield future.result()
[2017-04-24 07:07:21.294000] WARNING: __main__:   File "C:\Python27\lib\site-packages\concurrent\futures\_base.py", line 429, in result
[2017-04-24 07:07:21.294000] WARNING: __main__:     return self.__get_result()
[2017-04-24 07:07:21.295000] WARNING: __main__:   File "C:\Python27\lib\site-packages\concurrent\futures\thread.py", line 62, in run
[2017-04-24 07:07:21.295000] WARNING: __main__:     result = self.fn(*self.args, **self.kwargs)
[2017-04-24 07:07:21.295000] WARNING: __main__:   File "C:\Python27\lib\site-packages\esipy\client.py", line 140, in _multi_shim
[2017-04-24 07:07:21.295000] WARNING: __main__:     opt=opt,
[2017-04-24 07:07:21.296000] WARNING: __main__:   File "C:\Python27\lib\site-packages\esipy\client.py", line 99, in _retry_request
[2017-04-24 07:07:21.296000] WARNING: __main__:     res = self._request(req_and_resp, **kwargs)
[2017-04-24 07:07:21.296000] WARNING: __main__:   File "C:\Python27\lib\site-packages\esipy\client.py", line 211, in _request
[2017-04-24 07:07:21.296000] WARNING: __main__:     stream=True
[2017-04-24 07:07:21.297000] WARNING: __main__:   File "C:\Python27\lib\site-packages\requests\sessions.py", line 596, in send
[2017-04-24 07:07:21.297000] WARNING: __main__:     r = adapter.send(request, **kwargs)
[2017-04-24 07:07:21.297000] WARNING: __main__:   File "C:\Python27\lib\site-packages\requests\adapters.py", line 497, in send
[2017-04-24 07:07:21.297000] WARNING: __main__:     raise SSLError(e, request=request)
```

This is 100% due to spotty network (weak wifi signal, unreliable AP, pretty close to worse possible scenario).  I was doing about 11-12k queries per run, and would see this happen maybe an average of 1 in 3 runs.

So yeah, I think that this is good and I ran it by SnowedIn to see what he thought (since he worked on the retry bit in the first place).  We're _only_ catching connection related exceptions, so we won't catch if there's malformed/missing request/etc.


>Also, regarding the commits themself, can't you use a pyswagger.io.Response object instead of creating a whole new class ?

Uhhh, probably? Didn't think of that. :D

**Comment by Kyria** [comment]
So... actually you are catching client side (requests.session to be precise) connection timeout, not server side one.
Then ok, but please, at least fix travis. 

For the object thing, this might work (didn't test it, don't have the time for it this evening)
```python
try:
    res = self._request(req_and_resp, **kwargs)
except (RequestsConnectionError, Timeout) as e:
    req, res = req_and_resp  # this is a tuple of pyswagger.io.Request, and Response, so you can use it :)
    res.status = 500
    res._Response__path = req._Request__path  # request__path is the same as response, and is always set
    
    try:
        res.data = e.message.message
    except AttributeError:
        res.data = ""
```

**Comment by Ebag333** [comment]
>Then ok, but please, at least fix travis.

psure that these tests aren't failing because of this code.

One, those tests run fine locally.  OTOH there's two tests that won't run on my box.https://puu.sh/vuYuD/688f1abd29.png

I can try using the object. :)

**Comment by Ebag333** [comment]
Either travis or your tests are setup weird. :/

` no environment variables set`

That's not my fault!

**Pull request merged**
