### PR TITLE
Update security.py

### PR DESCRIPTION
**Pull request by leesolway**
Add audience attribute to fix a CCP breaking change

### CODE REVIEW

**Comment by Kyria** [comment]
ty for the update :)

**Comment by mckernanin** [comment]
@Kyria are you going to tag a release for this?

**Comment by Kyria** [comment]
i will, just didn't have the time yet. i'll try to do it tomorrow (if I don't forget)

**Comment by Kyria** [comment]
sorry for the delay, it should be released in pypi now @mckernanin

**Pull request merged**
